# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    quai_pictures:
      uri_prefix: "%quai_pictures%"
      upload_destination: "%kernel.project_dir%/public/uploads/pictures"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
